
development:
  adapter: mysql2
  encoding: utf8
  database: busted_server
  pool: 5
  username: busted_server
  password: zdgzvbzkt9

test:
  adapter: mysql2
  encoding: utf8
  database: busted_server
  pool: 5
  username: busted_server
  password: zdgzvbzkt9

production:
  adapter: mysql2
  encoding: utf8
  database: busted_server
  pool: 5
  host: ip-10-31-199-254.ec2.internal
  username: busted_server
  password: zdgzvbzkt9
