
development:
  adapter: mysql2
  encoding: utf8
  database: busted_server
  pool: 5
  username: busted_server
  password: zdgzvbzkt9

test:
  adapter: mysql2
  encoding: utf8
  database: busted_server
  pool: 5
  username: busted_server
  password: zdgzvbzkt9

production:
  adapter: mysql2
  encoding: utf8
  database: busted_server
  pool: 5
  host: 50.16.8.136
  username: busted_server
  password: zdgzvbzkt9
