development: &dev
  zip_url: http://localhost/google_transit.zip
  precision_formats:
    paths: "%0.10f"
    stops: "%0.6f"

test: *dev

production:
  zip_url: http://www.halifax.ca/metrotransit/googletransitfeed/google_transit.zip
  precision_formats:
    paths: "%0.10f"
    stops: "%0.6f"
