common: &default_settings
  license_key: '<%= SECRETS["api_keys"]["new_relic"] %>'
  agent_enabled: auto
  app_name: KNOWtime Server
  monitor_mode: true
  developer_mode: false
  log_level: info

  browser_monitoring:
      auto_instrument: false

  # See: https://newrelic.com/docs/ruby/audit-log
  audit_log:
    enabled: false

  capture_params: false

  transaction_tracer:
    enabled: false
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500


  error_collector:
    enabled: true
    capture_source: true
    ignore_errors: "ActionController::RoutingError,Sinatra::NotFound"

  capture_memcache_keys: true


# Application Environments
# ------------------------------------------

development:
  <<: *default_settings
  monitor_mode: false
  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
  monitor_mode: true

staging:
  <<: *default_settings
  monitor_mode: true
